// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAZ2GBx_qAi7p5EajjQ0qdA3z926YNA9U',
    appId: '1:144660153487:web:79cddf33f115a84f835cfa',
    messagingSenderId: '144660153487',
    projectId: 'chatapp-38d71',
    authDomain: 'chatapp-38d71.firebaseapp.com',
    storageBucket: 'chatapp-38d71.appspot.com',
    measurementId: 'G-8PCXB9XH96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHQIfCHJQ6ts6wPJpZnBoMG90-18c4-A',
    appId: '1:144660153487:android:648e62fd5d3e6fa1835cfa',
    messagingSenderId: '144660153487',
    projectId: 'chatapp-38d71',
    storageBucket: 'chatapp-38d71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyNr-KwDSFofy2sa5UUKJqIAuTTn2PZZg',
    appId: '1:144660153487:ios:55f57343cc1a9d96835cfa',
    messagingSenderId: '144660153487',
    projectId: 'chatapp-38d71',
    storageBucket: 'chatapp-38d71.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
